import Head from "next/head";
import { Box, Text, Button, VStack, useColorModeValue } from '@chakra-ui/react';
import Logo from '@/components/Logo';

export default function Home() {
  return (
    <>
      <Head>
        <title>★Biccas | by Xforeal★</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        as="main"
      >
        <VStack spacing={6} align="center" justify="center" minHeight="100vh">
          <Logo h={35} />
          <Box textAlign="center">
            <Text fontSize="10em" fontWeight="900" lineHeight="0.9" color="main">
              404
            </Text>
            <Text fontSize="lg" color={useColorModeValue("gray.600", "white")}>
              Oops! The page you are looking for does not exist.
            </Text>
          </Box>
          <Button as="a" href="/" variant="primary" size="lg">
            Go to Home
          </Button>
        </VStack>
      </Box>
    </>
  );
}
