import Head from "next/head";
import { Box } from '@chakra-ui/react';

import Hero from "@/components/Sections/_hero";
import Brands from "@/components/Sections/_brands";
import HowSection from "@/components/Sections/_how";
import Features from "@/components/Sections/_features";
import WhatSection from "@/components/Sections/_what";
import Plans from "@/components/Sections/_plan";
import Contacts from "@/components/Sections/_contacts";

export default function Home() {
  return (
    <>
      <Head>
        <title>★Biccas | by Xforeal★</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        as="main"
      >
        <Hero />
        <Brands />
        <HowSection />
        <Features />
        <WhatSection />
        <Plans />
        <Contacts />
      </Box>
    </>
  );
}
